### ISSUE TITLE
how about NameError("name 'unicode' is not defined",) 

### ISSUE THREAD

**Issue by wu-song** [2shou/PhantomjsFetcher#2]
Following your  instruction:
fetcher.phantomjs_fetch('http://www.baidu.com')
or other url, recive error like this:
ERROR:root:[599] http://www.baidu.com, NameError("name 'unicode' is not defined",) 3.12s

what's the problem?
thx!

**Comment by 2shou** [comment]
Pls try it again with Python 2.7. There are some differences in string api between 2 and 3.
